AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for S3 trigger

Resources:
  ProcessImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["app.lambda_handler"]
      Timeout: 900
      MemorySize: 5240
      Environment:
        Variables:
          AWS_DEFAULT_REGION: ap-south-1
          DYNAMODB_TABLE: Files  # Match the actual table name
          DYNAMODB_ENDPOINT: https://dynamodb.ap-south-1.amazonaws.com
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: 
                - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Files'
        - S3ReadPolicy:
            BucketName: kdg-raw
        - S3CrudPolicy:
            BucketName: !Ref DestinationBucket
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucket
            Events: s3:ObjectCreated:*
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hello_world
      DockerTag: python3.9-v1

  SourceBucket:
    Type: AWS::S3::Bucket
    
  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: final-cog

  MetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Files
      AttributeDefinitions:
        - AttributeName: Unique_Id
          AttributeType: S
        - AttributeName: acquisition_timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: Unique_Id
          KeyType: HASH
        - AttributeName: acquisition_timestamp
          KeyType: RANGE