AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: INSAT-3D Processing with Rollback Disabled

Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: false

Resources:
  # Lambda Function first
  ProcessImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["app.lambda_handler"]
      Timeout: 900
      MemorySize: 5240
      Environment:
        Variables:
          REGION: us-east-1
          DYNAMODB_TABLE: !Ref MetadataTable
          DESTINATION_BUCKET: !Ref DestinationBucket
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MetadataTable
        - S3ReadPolicy:
            BucketName: !Ref SourceBucket
        - S3CrudPolicy:
            BucketName: !Ref DestinationBucket
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./hello_world
      DockerTag: python3.9-v1

  # Basic resources without triggers
  SourceBucket:
    Type: AWS::S3::Bucket
    
  DestinationBucket:
    Type: AWS::S3::Bucket

  MetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-metadata"
      AttributeDefinitions:
        - AttributeName: Unique_Id
          AttributeType: S
        - AttributeName: acquisition_timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: Unique_Id
          KeyType: HASH
        - AttributeName: acquisition_timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  SourceBucketName:
    Description: "Source S3 Bucket"
    Value: !Ref SourceBucket
  DestinationBucketName:
    Description: "Destination S3 Bucket"
    Value: !Ref DestinationBucket
  MetadataTableName:
    Description: "DynamoDB Table"
    Value: !Ref MetadataTable
  FunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt ProcessImageFunction.Arn
